name: Build Artifacts

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build JAR
      run: ./gradlew jar
      
    - name: Generate build info
      run: |
        echo "Build Information" > build-info.txt
        echo "==================" >> build-info.txt
        echo "Branch: ${{ github.ref_name }}" >> build-info.txt
        echo "Commit: ${{ github.sha }}" >> build-info.txt
        echo "Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> build-info.txt
        echo "Java Version: $(java -version 2>&1 | head -n 1)" >> build-info.txt
        echo "" >> build-info.txt
        echo "JAR Files:" >> build-info.txt
        ls -la build/libs/*.jar >> build-info.txt
        
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: co-organizer-jar-${{ github.ref_name }}-${{ github.run_number }}
        path: |
          build/libs/*.jar
          build-info.txt
        retention-days: 30
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports-${{ github.ref_name }}-${{ github.run_number }}
        path: |
          build/reports/tests/test/
          build/test-results/test/
        retention-days: 7