name: OpenAPI Validation

on:
  push:
    branches: [ main ]
    paths: [ 'openapi.yaml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'openapi.yaml' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate OpenAPI specification
      uses: char0n/swagger-editor-validate@v1
      with:
        definition-file: openapi.yaml
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Swagger CLI
      run: npm install -g @apidevtools/swagger-cli
      
    - name: Validate with Swagger CLI
      run: swagger-cli validate openapi.yaml
      
    - name: Bundle OpenAPI spec
      run: swagger-cli bundle openapi.yaml --outfile openapi-bundled.yaml --type yaml
      
    - name: Upload bundled spec
      uses: actions/upload-artifact@v4
      with:
        name: openapi-bundled
        path: openapi-bundled.yaml