name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Validate with tests
      run: ./gradlew test
      
    - name: Build JAR
      run: ./gradlew jar
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Co-Organizer ${{ steps.get_version.outputs.VERSION }}
          
          ### Installation
          1. Download `co-organizer.jar` below
          2. In Burp Suite: Extensions > Installed > Add
          3. Select the JAR file and click Next
          
          ### What's New
          See the commit history for details of changes in this release.
          
          ### Requirements
          - Burp Suite Professional or Community (2023.1+)
          - Java 21+ (included with modern Burp)
        files: |
          build/libs/*.jar
        generate_release_notes: true
        draft: false
        prerelease: false
        
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-jar-${{ steps.get_version.outputs.VERSION }}
        path: build/libs/*.jar